# Generated by Django 4.1 on 2022-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_profileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
