# Generated by Django 4.1 on 2022-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_post_post_type_post_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_title',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('images', 'Images'), ('text', 'text')], default='None', max_length=100),
        ),
    ]
