# Generated by Django 4.1 on 2022-08-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_postlikes_like_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='like_status',
            field=models.BooleanField(choices=[('like', 'Like'), ('unlike', 'UnLike')], default=False),
        ),
    ]
