# Generated by Django 4.1 on 2022-08-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_post_caption_alter_postlikes_like_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
