# Generated by Django 4.1 on 2022-08-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_postlikes_post_alter_postlikes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dis_likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
