# Generated by Django 4.1 on 2022-08-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_profileupload_bio_alter_profileupload_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
