# Generated by Django 4.1 on 2022-08-30 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0014_friend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='UserProfile'),
        ),
    ]
