# Generated by Django 4.1 on 2022-08-31 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0016_profileupload_cover_img_profileupload_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileupload',
            name='cover_img',
            field=models.ImageField(default='', upload_to='cover_image'),
        ),
        migrations.AlterField(
            model_name='profileupload',
            name='img',
            field=models.ImageField(default='', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profileupload',
            name='profileuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
