# Generated by Django 4.1 on 2022-09-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0017_alter_profileupload_cover_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileupload',
            name='profileuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
