# Generated by Django 4.1 on 2022-09-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_rename_friend_friendlist_remove_postmedia_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feeling_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
