# Generated by Django 4.1 on 2022-09-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_post_feeling_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feeling_activity',
        ),
    ]
