# Generated by Django 4.1 on 2022-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='like_status',
            field=models.BooleanField(default=False),
        ),
    ]
