# Generated by Django 4.1 on 2022-09-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_alter_post_postuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='like_status',
        ),
        migrations.AddField(
            model_name='postlikes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('UnLike', 'UnLike')], default='Like', max_length=10),
        ),
    ]
