# Generated by Django 4.1 on 2022-09-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='comment_reply',
        ),
    ]
