# Generated by Django 4.1 on 2022-09-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_remove_postcomment_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='task.postcomment'),
        ),
    ]
