# Generated by Django 4.1 on 2022-09-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_postcomment_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='comment_reply',
        ),
    ]
