# Generated by Django 4.1 on 2022-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0029_remove_postcomment_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='comment_status',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
