# Generated by Django 4.1 on 2022-09-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0031_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
