# Generated by Django 4.1 on 2022-09-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_profileupload_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('accepted', 'Accepted')], default=2, max_length=8),
            preserve_default=False,
        ),
    ]
