# Generated by Django 4.1 on 2022-09-11 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0035_remove_profileupload_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileupload',
            name='pro_friends',
        ),
        migrations.AddField(
            model_name='profileupload',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
