# Generated by Django 4.1 on 2022-09-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0036_alter_friendlist_friend_alter_friendlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='task.profileupload'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfriend', to='task.profileupload'),
        ),
    ]
