# Generated by Django 4.1 on 2022-09-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0036_remove_profileupload_friends_and_more'),
        ('task', '0036_remove_profileupload_pro_friends_and_more'),
        ('task', '0037_alter_friendlist_friend_alter_friendlist_user'),
    ]

    operations = [
    ]
