# Generated by Django 4.1 on 2022-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0039_remove_profileupload_pro_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], default='send', max_length=8),
        ),
    ]
