# Generated by Django 4.1 on 2022-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0040_alter_friendlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], default='send', max_length=8, null=True),
        ),
    ]
