# Generated by Django 4.0.6 on 2022-09-15 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0041_alter_friendlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='commentliked',
            field=models.ManyToManyField(blank=True, default=None, related_name='commentliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
