# Generated by Django 4.0.6 on 2022-09-15 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0042_postcomment_commentliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='commentliked',
            field=models.ManyToManyField(blank=True, default=None, related_name='likecomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ok', to=settings.AUTH_USER_MODEL),
        ),
    ]
